POST http://localhost:8080/api/sites
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Implbm5pZW1tb25kYXlAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY3NDk2NjE3MCwiZXhwIjoxNjc0OTY5NzcwfQ.0l_4-C4AxPVST7rDzo_k6VOSUFJqHCL5vq1LTzvxZuA


{
  "address": "150 Kingston Pike",
  "lat": "1.142",
  "long": "2.223",
  "imgPath": "generic5.jpg",
  "userId": 1
}

###
POST http://localhost:8080/api/sites
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Implbm5pZW1tb25kYXlAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY3NDk2NjE3MCwiZXhwIjoxNjc0OTY5NzcwfQ.0l_4-C4AxPVST7rDzo_k6VOSUFJqHCL5vq1LTzvxZuA


{
  "address": "204 Walnut St",
  "lat": "1.142",
  "long": "2.223",
  "imgPath": "generic4.jpg",
  "userId": 1
}