POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Jennie",
  "lastName": "Monday",
  "phone": "4324137234",
  "email": "jenniemmonday@gmail.com",
  "password": "topsecret"
}