POST http://localhost:8080/api/sites
Content-Type: application/json

{
  "address": "150 Kingston Pike",
  "lat": "1.142",
  "long": "2.223",
  "imgPath": "generic5.jpg",
  "ownerId": 1
}

###
POST http://localhost:8080/api/sites
Content-Type: application/json

{
  "address": "200 Walnut St",
  "lat": "1.142",
  "long": "2.223",
  "imgPath": "generic4.jpg",
  "ownerId": 1
}